


############################################################################
#
# AVI CONFIDENTIAL
# __________________
#
# [2013] - [2018] Avi Networks Incorporated
# All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains the property
# of Avi Networks Incorporated and its suppliers, if any. The intellectual
# and technical concepts contained herein are proprietary to Avi Networks
# Incorporated, and its suppliers and are covered by U.S. and Foreign
# Patents, patents in process, and are protected by trade secret or
# copyright law, and other laws. Dissemination of this information or
# reproduction of this material is strictly forbidden unless prior written
# permission is obtained from Avi Networks Incorporated.
###

pb_ordered = [
    'ControllerLicense',
    'GslbSite',
    'SeProperties',
    'UserActivity',
    'SecureChannelToken',
    'FloatingIpSubnet',
    'UserAccountProfile',
    'SecureChannelMapping',
    'VIMgrIPSubnetRuntime',
    'SecureChannelAvailableLocalIPs',
    'ControllerProperties',
    'GslbThirdPartySite',
    'Tenant',
    'VsApicExtension',
    'CloudProperties',
    'CertificateManagementProfile',
    'Role',
    'AuthProfile',
    'CloudConnectorUser',
    'CloudRuntime',
    'VIPGNameInfo',
    'SnmpTrapProfile',
    'HardwareSecurityModuleGroup',
    'VIDCInfo',
    'Gslb',
    'SCVsStateInfo',
    'GslbGeoDbProfile',
    'SCPoolServerStateInfo',
    'ApplicationPersistenceProfile',
    'ErrorPageBody',
    'NetworkRuntime',
    'DebugController',
    'AutoScaleLaunchConfig',
    'AnalyticsProfile',
    'LogControllerMapping',
    'Webhook',
    'VIMgrControllerRuntime',
    'StringGroup',
    'Cluster',
    'DebugServiceEngine',
    'PKIProfile',
    'JobEntry',
    'MicroService',
    'APICLifsRuntime',
    'AlertSyslogConfig',
    'SSLProfile',
    'WafProfile',
    'CustomIpamDnsProfile',
    'AlertObjectList',
    'AlertScriptConfig',
    'NetworkProfile',
    'IpAddrGroup',
    'ClusterCloudDetails',
    'BackupConfiguration',
    'SSLKeyAndCertificate',
    'ErrorPageProfile',
    'MicroServiceGroup',
    'WafPolicy',
    'IpamDnsProviderProfile',
    'DnsPolicy',
    'ApplicationProfile',
    'Scheduler',
    'SystemConfiguration',
    'HealthMonitor',
    'NetworkSecurityPolicy',
    'Cloud',
    'Backup',
    'AlertEmailConfig',
    'GslbService',
    'VrfContext',
    'PriorityLabels',
    'PoolGroupDeploymentPolicy',
    'VIMgrVMRuntime',
    'DebugVirtualService',
    'ActionGroupConfig',
    'VIMgrHostRuntime',
    'AlertConfig',
    'VIMgrNWRuntime',
    'VIMgrClusterRuntime',
    'VIMgrSEVMRuntime',
    'ServerAutoScalePolicy',
    'Network',
    'VIMgrDCRuntime',
    'VsVip',
    'TrafficCloneProfile',
    'ServiceEngineGroup',
    'Pool',
    'VIMgrVcenterRuntime',
    'ServiceEngine',
    'PoolGroup',
    'HTTPPolicySet',
    'VSDataScriptSet',
    'L4PolicySet',
    'VirtualService',
    'Application',
    'Alert',
]

pb_skip_datastore = {
    'UserActivity',
    'UserAccountProfile',
    'SCPoolServerStateInfo',
    'JobEntry',
    'APICLifsRuntime',
    'AlertSyslogConfig',
    'AlertObjectList',
    'AlertScriptConfig',
    'BackupConfiguration',
    'Scheduler',
    'Backup',
    'AlertEmailConfig',
    'Alert',
}

config_models = [
    'MicroService',
    'CustomIpamDnsProfile',
    'SystemConfiguration',
    'NetworkSecurityPolicy',
    'VirtualService',
    'VsVip',
    'PoolGroup',
    'SeProperties',
    'IpamDnsProviderProfile',
    'GslbGeoDbProfile',
    'Cloud',
    'ServiceEngineGroup',
    'Network',
    'AlertSyslogConfig',
    'AlertScriptConfig',
    'AlertEmailConfig',
    'AlertConfig',
    'ActionGroupConfig',
    'AlertObjectList',
    'SnmpTrapProfile',
    'WafPolicy',
    'VSDataScriptSet',
    'Application',
    'NetworkProfile',
    'DnsPolicy',
    'ClusterCloudDetails',
    'ErrorPageProfile',
    'ErrorPageBody',
    'IpAddrGroup',
    'StringGroup',
    'MicroServiceGroup',
    'ControllerProperties',
    'CloudConnectorUser',
    'Webhook',
    'TrafficCloneProfile',
    'AuthProfile',
    'WafProfile',
    'SSLKeyAndCertificate',
    'SSLProfile',
    'PKIProfile',
    'CertificateManagementProfile',
    'ApplicationPersistenceProfile',
    'L4PolicySet',
    'VrfContext',
    'Scheduler',
    'BackupConfiguration',
    'HardwareSecurityModuleGroup',
    'Pool',
    'ServerAutoScalePolicy',
    'AutoScaleLaunchConfig',
    'ApplicationProfile',
    'HealthMonitor',
    'PoolGroupDeploymentPolicy',
    'AnalyticsProfile',
    'CloudProperties',
    'HTTPPolicySet',
    'UserAccountProfile',
    'Role',
    'Tenant',
    'PriorityLabels',
]
